ci: Code review changes
1. Move github.ref_name to an env variable to allow the shell to ignore the
   contents.
2. Catch skopeo failures
3. Login on release actions

diff --git a/.github/workflows/build_container.yaml b/.github/workflows/build_container.yaml
--- a/.github/workflows/build_container.yaml
+++ b/.github/workflows/build_container.yaml
@@ -7,6 +7,7 @@ on:
 env:
   IMAGE_REGISTRY: quay.io
   IMAGE_NAME: zathras/zathras
+  RELEASE_TAG: ${{ github.ref_name }}
 
 jobs:
   containerize:
@@ -15,7 +16,7 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Login to Quay
-        if: github.event_name == 'push'
+        if: github.event_name == 'push' || github.event_name == 'release'
         uses: docker/login-action@v3
         with:
           registry: ${{ env.IMAGE_REGISTRY }}
@@ -33,17 +34,23 @@ jobs:
           if [[ "${{ github.event_name }}" == "push" ]]; then
             IMAGE_TAGS="${IMAGE_TAGS},${IMAGE_BASE}:latest"
           elif [[ "${{ github.event_name }}" == "release" ]]; then
-            LOCAL_MAJOR=$(echo "${{ github.ref_name }}" | cut -d'.' -f1)
-            LOCAL_MINOR=$(echo "${{ github.ref_name }}" | cut -d'.' -f2)
-            LOCAL_PATCH=$(echo "${{ github.ref_name }}" | cut -d'.' -f3)
+            LOCAL_MAJOR=$(echo "$RELEASE_TAG" | cut -d'.' -f1)
+            LOCAL_MINOR=$(echo "$RELEASE_TAG" | cut -d'.' -f2)
+            LOCAL_PATCH=$(echo "$RELEASE_TAG" | cut -d'.' -f3)
             
+
+            REMOTE_JSON=$(skopeo list-tags docker://$IMAGE_BASE)
+            if [[ $? -ne 0 ]]; then
+              echo "::error::Could not query $IMAGE_BASE for image tags"
+              exit 1
+            fi
             # Don't care about other majors
-            REMOTE_TAGS=$( (skopeo list-tags docker://$IMAGE_BASE | jq -r '.Tags[]' | grep -E "^$LOCAL_MAJOR\.") || echo "" && echo "${{ github.ref_name }}")
-            if [[ $(echo "$REMOTE_TAGS" | sort -V | tail -n1) == "${{ github.ref_name}}" ]]; then
+            REMOTE_TAGS=$(echo "$REMOTE_JSON" | jq -r '.Tags[]' | grep -E "^$LOCAL_MAJOR\." || echo ""; echo "$RELEASE_TAG")
+            if [[ $(echo "$REMOTE_TAGS" | sort -V | tail -n1) == "$RELEASE_TAG" ]]; then
               IMAGE_TAGS="${IMAGE_TAGS},${IMAGE_BASE}:${LOCAL_MAJOR}"
             fi
 
-            IMAGE_TAGS="${IMAGE_TAGS},${IMAGE_BASE}:${LOCAL_MAJOR}.${LOCAL_MINOR},${IMAGE_BASE}:${{ github.ref_name }}"
+            IMAGE_TAGS="${IMAGE_TAGS},${IMAGE_BASE}:${LOCAL_MAJOR}.${LOCAL_MINOR},${IMAGE_BASE}:$RELEASE_TAG"
           fi
           echo "$IMAGE_TAGS"
           echo "IMAGE_TAGS=$IMAGE_TAGS" >> $GITHUB_ENV
