Fix: Add check for jq within enviornment

diff --git a/.github/workflows/pullhero.yaml b/.github/workflows/pullhero.yaml
--- a/.github/workflows/pullhero.yaml
+++ b/.github/workflows/pullhero.yaml
@@ -19,8 +19,15 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Install pullhero
-        run: pip3 install pullhero
+        run: pip3 install pullhero || (echo "::error title=Pullhero Error::Pullhero failed to install" && exit 1)
       
+      - name: Verify jq is installed
+        run: |
+          if ! command -v jq &> /dev/null; then
+            echo "::error title=jq Error::jq could not be found"
+            exit 1
+          fi
+
       - name: Get pull request details
         if: github.event_name == 'pull_request'
         run: |
@@ -31,7 +38,6 @@ jobs:
       - name: Get PR Details (comment)
         if: github.event_name == 'issue_comment'
         run: |
-          set -e # Exit if any jq command fails
           echo "PR_NUMBER=$(jq -r '.issue.pull_request.number' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
           echo "BASE_BRANCH=$(jq -r '.issue.pull_request.base.ref' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
           echo "HEAD_BRANCH=$(jq -r '.issue.pull_request.head.ref' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
